# Generated by Django 3.2.9 on 2021-11-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(blank=True, choices=[('1m', '1 minute (interval)'), ('3m', '3 minutes (interval)'), ('5m', '5 minutes (interval)'), ('15m', '15 minutes (interval)'), ('30m', '30 minutes (interval)'), ('1h', '1 hour (interval)'), ('2h', '2 hours (interval)'), ('4h', '4 hours (interval)'), ('6h', '6 hours (interval)'), ('8h', '8 hours (interval)'), ('12h', '12 hours (interval)'), ('1d', '1 day (interval)'), ('1w', '1 week (interval)'), ('1M', '1 month (interval)')], max_length=255, null=True)),
                ('open_time', models.DateTimeField(blank=True, null=True, verbose_name='Open Time')),
                ('open_price', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, verbose_name='Open Price')),
                ('highest_price', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, verbose_name='Highest Price')),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, verbose_name='Lowest Price')),
                ('close_price', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, verbose_name='Close Price')),
                ('volume', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, verbose_name='Volume')),
                ('close_time', models.DateTimeField(blank=True, null=True, verbose_name='Close Time')),
                ('quote_asset_volume', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, verbose_name='Quote Asset Volume')),
                ('number_of_trades', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Number of Trades')),
                ('taker_buy_base_asset_volume', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, verbose_name='Taker Buy Base Asset Volume')),
                ('taker_buy_quote_asset_volume', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, verbose_name='Taker Buy Base Asset Volume')),
                ('ignore', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True, verbose_name='Ignore')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kline',
                'verbose_name_plural': 'Klines',
            },
        ),
    ]
