# Generated by Django 3.2.9 on 2021-11-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kline',
            name='timestamp',
            field=models.PositiveBigIntegerField(default=True, null=True, verbose_name='Timestamp'),
        ),
    ]
