# Generated by Django 3.2.9 on 2021-11-19 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
        ('data_types', '0002_kline_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='kline',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coins.coin'),
        ),
    ]
