# Generated by Django 3.2.9 on 2021-11-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_types', '0003_kline_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kline',
            name='close_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Close Price'),
        ),
        migrations.AlterField(
            model_name='kline',
            name='highest_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Highest Price'),
        ),
        migrations.AlterField(
            model_name='kline',
            name='ignore',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Ignore'),
        ),
        migrations.AlterField(
            model_name='kline',
            name='lowest_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Lowest Price'),
        ),
        migrations.AlterField(
            model_name='kline',
            name='open_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Open Price'),
        ),
        migrations.AlterField(
            model_name='kline',
            name='quote_asset_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Quote Asset Volume'),
        ),
        migrations.AlterField(
            model_name='kline',
            name='taker_buy_base_asset_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Taker Buy Base Asset Volume'),
        ),
        migrations.AlterField(
            model_name='kline',
            name='taker_buy_quote_asset_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Taker Buy Base Asset Volume'),
        ),
        migrations.AlterField(
            model_name='kline',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Volume'),
        ),
    ]
