# Generated by Django 3.2.9 on 2021-11-19 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('BTCUSDT', 'Bitcoin/USD'), ('ETHUSDT', 'Etherium/USD'), ('BNBUSDT', 'Binance Coin/USD')], max_length=50, verbose_name='Symbol')),
                ('current_price', models.DecimalField(decimal_places=5, max_digits=19, verbose_name='Current Price')),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Coins',
            },
        ),
        migrations.CreateModel(
            name='CoinPriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=5, max_digits=19, verbose_name='Price')),
                ('change', models.DecimalField(decimal_places=5, max_digits=19, verbose_name='Change')),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coins.coin')),
            ],
            options={
                'verbose_name': 'Coin Price Change',
                'verbose_name_plural': 'Coin Price Changes',
            },
        ),
    ]
