# Generated by Django 3.2.9 on 2021-11-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_auto_20211119_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Current Price'),
        ),
        migrations.AlterField(
            model_name='coinpricechange',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Change'),
        ),
        migrations.AlterField(
            model_name='coinpricechange',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Price'),
        ),
    ]
