# Generated by Django 3.2.9 on 2021-12-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_alter_coinpricechange_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinpricechange',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
