# Generated by Django 3.2.9 on 2021-12-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0007_coinpricechange_change_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(choices=[('BTCUSDT', 'Bitcoin/USD'), ('ETHUSDT', 'Etherium/USD'), ('BNBUSDT', 'Binance Coin/USD'), ('XRPUSDT', 'Ripple/USD'), ('ADAUSDT', 'Cardano/USD'), ('XLMUSDT', 'Stellar/USD'), ('DOGEUSDT', 'Doge/USD')], max_length=50, verbose_name='Symbol'),
        ),
    ]
