# Generated by Django 3.2.9 on 2021-12-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0008_alter_coin_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='current_price',
            field=models.DecimalField(decimal_places=6, max_digits=19, verbose_name='Current Price'),
        ),
    ]
