# Generated by Django 3.2.9 on 2022-01-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0012_alter_coin_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='current_price',
            field=models.DecimalField(decimal_places=11, max_digits=19, verbose_name='Current Price'),
        ),
    ]
