# Generated by Django 3.2.9 on 2021-12-19 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decision_maker', '0005_auto_20211219_0305'),
        ('coins', '0011_auto_20211218_0023'),
        ('wallet', '0006_alter_wallet_coin_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='coin_balance',
        ),
        migrations.AddField(
            model_name='wallet',
            name='decision_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='decision_maker.decisionsetting', verbose_name='Decision Settings of Wallet'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='wallet_identifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wallet Identifier'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='name',
            field=models.CharField(default='A wallet', max_length=255, verbose_name='Wallet Name'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_balance',
            field=models.DecimalField(decimal_places=11, max_digits=19, verbose_name='Total Balance'),
        ),
        migrations.CreateModel(
            name='CoinAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=11, default=0, max_digits=19, verbose_name='Coin Balance')),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coins.coin')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coin_assets', to='wallet.wallet', verbose_name='Wallet With')),
            ],
            options={
                'verbose_name': 'Coin Asset',
                'verbose_name_plural': 'Coin Assets',
            },
        ),
    ]
