# Generated by Django 3.2.9 on 2021-12-19 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_auto_20211219_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='decision_settings',
            new_name='decision_setting',
        ),
    ]
