# Generated by Django 3.2.9 on 2021-12-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_maker', '0006_decision_wallet'),
        ('wallet', '0008_rename_decision_settings_wallet_decision_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='decision_setting',
        ),
        migrations.AddField(
            model_name='wallet',
            name='decision_setting',
            field=models.ManyToManyField(blank=True, related_name='wallets', to='decision_maker.DecisionSetting', verbose_name='Decision Settings of Wallet'),
        ),
    ]
