# Generated by Django 3.2.9 on 2021-12-04 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coins', '0006_alter_coinpricechange_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio_to_sell', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Ratio to Sell')),
                ('ratio_to_buy', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Ratio to Buy')),
            ],
            options={
                'verbose_name': 'Decision Setting',
                'verbose_name_plural': 'Decision Settings',
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_level', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Decided Price Level')),
                ('type_of_decision', models.CharField(blank=True, choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=255, null=True, verbose_name='Type of Decision')),
                ('income_ratio', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Income by Decision')),
                ('coin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coins.coin', verbose_name='Coin to Decide')),
            ],
            options={
                'verbose_name': 'Decision',
                'verbose_name_plural': 'Decisions',
            },
        ),
    ]
