# Generated by Django 3.2.9 on 2021-12-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionsetting',
            name='dont_by',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='decisionsetting',
            name='entry_price_level',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True, verbose_name='Entry Price Level'),
        ),
        migrations.AlterField(
            model_name='decisionsetting',
            name='ratio_to_buy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Ratio to Buy'),
        ),
    ]
