# Generated by Django 3.2.9 on 2021-12-04 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0006_alter_coinpricechange_created'),
        ('decision_maker', '0002_auto_20211204_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionsetting',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coins.coin', verbose_name='Coin to Decide'),
        ),
    ]
