# Generated by Django 3.2.9 on 2021-12-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_maker', '0003_decisionsetting_coin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decisionsetting',
            old_name='dont_by',
            new_name='dont_buy',
        ),
        migrations.AddField(
            model_name='decisionsetting',
            name='dont_sell',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='decision',
            name='income_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Income by Decision'),
        ),
    ]
