# Generated by Django 3.2.9 on 2021-12-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_maker', '0004_auto_20211204_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionsetting',
            name='dont_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='decisionsetting',
            name='dont_sell',
            field=models.BooleanField(default=False),
        ),
    ]
