# Generated by Django 3.2.9 on 2021-12-19 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_rename_decision_settings_wallet_decision_setting'),
        ('decision_maker', '0005_auto_20211219_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet', verbose_name='Wallet Decided'),
        ),
    ]
