# Generated by Django 3.2.9 on 2021-12-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_maker', '0007_auto_20211219_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionsetting',
            name='allocated_money_amount',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=19, null=True, verbose_name='Allocated Money'),
        ),
    ]
