# Generated by Django 3.2.9 on 2022-01-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_maker', '0008_alter_decisionsetting_allocated_money_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='decisionsetting',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='decisionsetting',
            name='dont_buy',
            field=models.BooleanField(default=False, verbose_name="Don't buy"),
        ),
        migrations.AlterField(
            model_name='decisionsetting',
            name='dont_sell',
            field=models.BooleanField(default=False, verbose_name="Don't sell"),
        ),
    ]
