# Generated by Django 3.2.9 on 2021-12-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='highest_ratio_point',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=19, null=True, verbose_name='Highest Ratio Point'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='lowest_ratio_point',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=19, null=True, verbose_name='Lowest Ratio Point'),
        ),
    ]
