# Generated by Django 3.2.9 on 2022-01-03 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_subscription_target_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Has been read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(default='Notification from Dobot.', max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=255, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.EmailValidator()], verbose_name='Email subscribed'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='highest_ratio_point',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=19, null=True, validators=[django.core.validators.DecimalValidator(19, 11)], verbose_name='Highest Ratio Point'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='lowest_ratio_point',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=19, null=True, validators=[django.core.validators.DecimalValidator(19, 11)], verbose_name='Lowest Ratio Point'),
        ),
    ]
